on:
  push:

jobs:
  release:
    name: "Create release"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Checkout current branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - run: 'echo "${{github.event.pull_request.body}}"'
      - uses: actions/github-script@v6
        with:
          script: |
            let number;
            console.log(process.env.GITHUB_EVENT_PATH)
            switch('${{ github.event_name}}') {
                case 'push':
                    const { stdout } = await exec.getExecOutput('jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH"',undefined)
                    console.log(stdout)
                    break
                case 'pull_request':
                    number = '${{ github.event.number }}'
                    break
            }
            if (number === ''){
                throw 'Could not determine PR number.'
            }
            console.log(JSON.stringify(${{github.event}}))
            const description = await github.rest.pulls.get({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: 7
            })
            console.log(description.data.body)
